
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  Terraform_Dev:
    name: Terraform Plan & Apply Dev
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      working-directory: ./dev
      run: terraform init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: './dev'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Terraform validate
      working-directory: ./dev
      run: terraform validate

    - name: Terraform Apply
      working-directory: ./dev
      run: terraform apply -auto-approve
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: './dev'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name : push changes
      run : |
        git commit -a
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  Terraform_Stage:
#    name: Terraform Plan & Apply Stage
#    runs-on: ubuntu-latest
#    steps:
#
#      - name: Checkout Repo
#        uses: actions/checkout@v2
#
#      - name: Terraform Setup
#        uses: hashicorp/setup-terraform@v1
#
#      - name: Terraform Init
#        working-directory: ./stage
#        run: terraform init
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          TF_ACTION_WORKING_DIR: './stage'
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#
#      - name: Terraform validate
#        working-directory: ./stage
#        run: terraform validate
#
#      - name: Terraform Apply
#        working-directory: ./stage
#        run: terraform apply -auto-approve
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          TF_ACTION_WORKING_DIR: './stage'
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
